name: app_links_workspace

environment:
  sdk: ^3.10.0

publish_to: none

dev_dependencies:
  melos: ^7.3.0

workspace:
  - app_links
  - app_links/example
  - app_links_linux
  - app_links_platform_interface
  - app_links_web

melos:
  # Don't generate intellij files
  ide:
    intellij: false

  command:
    # When a dependency in a package is listed it will be replaced with the following versions.
    bootstrap:
      environment:
        sdk: ^3.10.0
        flutter: ">=3.38.1"
      dev_dependencies:
        # Linter rules (https://pub.dev/packages/flutter_lints)
        flutter_lints: ^6.0.0

  clean:
    hooks:
      # Runs "flutter clean" in all Flutter packages (`--flutter`) with concurrency
      post: melos exec --flutter -c 1 -- "flutter clean"