name: app_links
description: Android App Links, Deep Links, iOs Universal Links and Custom URL schemes handler for Flutter (desktop included).
version: 3.4.3
homepage: https://github.com/llfbandit/app_links

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/plugin_platform_interface
  plugin_platform_interface: ^2.0.0

  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/lints
  lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.llfbandit.app_links
        pluginClass: AppLinksPlugin
      ios:
        pluginClass: AppLinksPlugin
      web:
        pluginClass: AppLinksPluginWeb
        fileName: src/app_links_web.dart
      windows:
        pluginClass: AppLinksPluginCApi
      macos:
        pluginClass: AppLinksMacosPlugin
