name: app_links_windows
description: App Links windows implementation.
version: 1.0.0
homepage: https://github.com/llfbandit/app_links/app_links_windows

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_links_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # https://pub.dev/packages/lints
  lints: ^1.0.1

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: AppLinksWindowsPlugin
