name: app_links_platform_interface
description: A common platform interface for the app_links plugin.
version: 2.0.2
homepage: https://github.com/llfbandit/app_links/tree/master/app_links_platform_interface

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.1"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  
  # https://pub.dev/packages/plugin_platform_interface
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^6.0.0
