name: app_links_platform_interface
description: A common platform interface for the app_links plugin.
version: 2.0.1
homepage: https://github.com/llfbandit/app_links/tree/master/app_links_platform_interface

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # https://pub.dev/packages/plugin_platform_interface
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_lints: ^4.0.0
