name: app_links_web
description: Web platform implementation of app_links plugin.
version: 1.0.3
homepage: https://github.com/llfbandit/app_links/tree/master/app_links_web

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  app_links_platform_interface: ^2.0.0

  web: ">=0.3.0 <2.0.0"

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  plugin:
    implements: app_links
    platforms:
      web:
        pluginClass: AppLinksPluginWeb
        fileName: "app_links_web.dart"
